### ISSUE TITLE
LibScanner.so

### ISSUE THREAD

**Issue by ankitag9** [jhansireddy/AndroidScannerDemo#1]
I was trying to modify the code to improve the edge detection algorithms but I those methods are not accessible as they are being used through libScanner.so. Is that an open source library?

**Comment by jhansireddy** [comment]
LibScanner.so is a native library, changing and performing an ndk build on ScanDemoExample/scanlibrary/src/main/jni/scan.cpp should reflect your changes in the LibScanner.so.

**Comment by ankitag9** [comment]
Thanx  a lot!!

**Comment by Bakhytzhan32** [comment]
Hello. This is very  good example. But there is one error. It not works if android version is biggger then 4.4.2. How to improve it. It some times works but simetimes says:
9073-9073/com.scanner.demo E/ActivityThread﹕ Performing stop of activity that is not resumed: {com.scanner.demo/com.scanlibrary.ScanActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.scanner.demo/com.scanlibrary.ScanActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3820)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3908)
            at android.app.ActivityThread.access$1200(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Please help me to correct it. Email address bakitcan32@gmail.com

**Comment by meysamfard** [comment]
Hi. I changed scan.cpp file in Android Studio and rebuild the app but hasn't any effect.
i just change this line:
 __android_log_print(ANDROID_LOG_VERBOSE, APPNAME, "MEYY Scaning getMagicColorBitmap");
