### ISSUE TITLE
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 11529204 bytes

### ISSUE THREAD

**Issue by makwanagopalmech** [jhansireddy/AndroidScannerDemo#119]
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 11529204)
2020-05-14 17:20:01.863 5819-5819/ E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 5819
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 11529204 bytes
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3873)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: android.os.TransactionTooLargeException: data parcel size 11529204 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:622)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3688)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3865)
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:165) 
        at android.app.ActivityThread.main(ActivityThread.java:6375) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by vamsee9** [comment]
what's the actual problem I can't get the error from your log
