### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bakhytzhan32** [jhansireddy/AndroidScannerDemo#4]
Hello. This is very good example. But there is one error. It not works if android version is biggger then 4.4.2. How to improve it. It some times works but simetimes says:
9073-9073/com.scanner.demo E/ActivityThread﹕ Performing stop of activity that is not resumed: {com.scanner.demo/com.scanlibrary.ScanActivity}
java.lang.RuntimeException: Performing stop of activity that is not resumed: {com.scanner.demo/com.scanlibrary.ScanActivity}
at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3820)
at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3908)
at android.app.ActivityThread.access$1200(ActivityThread.java:177)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5942)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

Please help me to correct it. Email address bakitcan32@gmail.com

**Comment by Aliabc123** [comment]
It's giving me error unfortunately scanlirary has stopped plz help me out.

[2016-01-05 00:11:38 - ScanActivity] ------------------------------
[2016-01-05 00:11:38 - ScanActivity] Android Launch!
[2016-01-05 00:11:38 - ScanActivity] adb is running normally.
[2016-01-05 00:11:38 - ScanActivity] No Launcher activity found!
[2016-01-05 00:11:38 - ScanActivity] The launch will only sync the application package on the device!
[2016-01-05 00:11:38 - ScanActivity] Performing sync
[2016-01-05 00:11:39 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:11:43 - ScanActivity] WARNING: Application does not specify an API level requirement!
[2016-01-05 00:11:43 - ScanActivity] Device API version is 17 (Android 4.2.1)
[2016-01-05 00:11:43 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:11:44 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:11:53 - ScanActivity] Success!
[2016-01-05 00:11:53 - ScanActivity] \ScanActivity\bin\ScanActivity.apk installed on device
[2016-01-05 00:11:53 - ScanActivity] Done!
[2016-01-05 00:14:16 - ScanActivity] ------------------------------
[2016-01-05 00:14:16 - ScanActivity] Android Launch!
[2016-01-05 00:14:16 - ScanActivity] adb is running normally.
[2016-01-05 00:14:16 - ScanActivity] No Launcher activity found!
[2016-01-05 00:14:16 - ScanActivity] The launch will only sync the application package on the device!
[2016-01-05 00:14:16 - ScanActivity] Performing sync
[2016-01-05 00:14:17 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:14:19 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:14:20 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:14:28 - ScanActivity] Success!
[2016-01-05 00:14:29 - ScanActivity] \ScanActivity\bin\ScanActivity.apk installed on device
[2016-01-05 00:14:29 - ScanActivity] Done!
[2016-01-05 00:16:51 - com.android.ide.eclipse.adt.internal.project.AndroidManifestHelper] Parser exception for C:\Users\Ali Hassan\Downloads\AndroidScannerDemo-master\AndroidScannerDemo-master\ScanDemoExample\scanlibrary\src\main\AndroidManifest.xml: The element type "activitys" must be terminated by the matching end-tag "</activitys>".
[2016-01-05 00:16:51 - ScanActivity] Error in an XML file: aborting build.
[2016-01-05 00:16:54 - ScanActivity] Parser exception for /ScanActivity/AndroidManifest.xml: The element type "activitys" must be terminated by the matching end-tag "</activitys>".
[2016-01-05 00:17:29 - ScanActivity] ------------------------------
[2016-01-05 00:17:29 - ScanActivity] Android Launch!
[2016-01-05 00:17:29 - ScanActivity] adb is running normally.
[2016-01-05 00:17:29 - ScanActivity] Performing com.scanlibrary.ScanActivity activity launch
[2016-01-05 00:17:29 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:17:46 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:17:47 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:17:55 - ScanActivity] Success!
[2016-01-05 00:17:55 - ScanActivity] Starting activity com.scanlibrary.ScanActivity on device 7DYPCIKVEEPN5PHE
[2016-01-05 00:17:57 - ScanActivity] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.scanlibrary/.ScanActivity }
[2016-01-05 00:19:39 - ScanActivity] ------------------------------
[2016-01-05 00:19:39 - ScanActivity] Android Launch!
[2016-01-05 00:19:39 - ScanActivity] adb is running normally.
[2016-01-05 00:19:39 - ScanActivity] Performing com.scanlibrary.ScanActivity activity launch
[2016-01-05 00:19:39 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:19:43 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:19:44 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:19:52 - ScanActivity] Success!
[2016-01-05 00:19:52 - ScanActivity] Starting activity com.scanlibrary.ScanActivity on device 7DYPCIKVEEPN5PHE
[2016-01-05 00:19:53 - ScanActivity] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.scanlibrary/.ScanActivity }
[2016-01-05 00:20:16 - ScanActivity] ------------------------------
[2016-01-05 00:20:16 - ScanActivity] Android Launch!
[2016-01-05 00:20:16 - ScanActivity] adb is running normally.
[2016-01-05 00:20:16 - ScanActivity] Performing com.scanlibrary.ScanActivity activity launch
[2016-01-05 00:20:16 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:20:19 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:20:20 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:20:27 - ScanActivity] Success!
[2016-01-05 00:20:27 - ScanActivity] Starting activity com.scanlibrary.ScanActivity on device 7DYPCIKVEEPN5PHE
[2016-01-05 00:20:27 - ScanActivity] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.scanlibrary/.ScanActivity }
[2016-01-05 00:20:35 - ScanActivity] ------------------------------
[2016-01-05 00:20:35 - ScanActivity] Android Launch!
[2016-01-05 00:20:35 - ScanActivity] adb is running normally.
[2016-01-05 00:20:35 - ScanActivity] Performing com.scanlibrary.ScanActivity activity launch
[2016-01-05 00:20:36 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:20:46 - ScanActivity] Launching a new emulator with Virtual Device 'Nexus_5_API_23_x86'
[2016-01-05 00:22:11 - Emulator] emulator: device fd:636
[2016-01-05 00:22:11 - Emulator] 
[2016-01-05 00:22:11 - Emulator] emulator: The memory needed by this AVD exceeds the max specified in your HAXM configuration.
[2016-01-05 00:22:11 - Emulator] emulator: AVD      RAM size = 1536 MB
[2016-01-05 00:22:11 - Emulator] emulator: HAXM max RAM size = 512 MB
[2016-01-05 00:22:11 - Emulator] emulator: You might want to adjust your AVD RAM size and/or HAXM configuration to run in fast virt mode.
[2016-01-05 00:22:11 - Emulator] 
[2016-01-05 00:22:11 - Emulator] HAXM is not working and emulator runs in emulation mode
[2016-01-05 00:22:14 - Emulator] creating window 43 59 329 583
[2016-01-05 00:22:14 - Emulator] emulator: emulator window was out of view and was recentered
[2016-01-05 00:22:14 - Emulator] 
[2016-01-05 00:22:15 - ScanActivity] New emulator found: emulator-5554
[2016-01-05 00:22:15 - ScanActivity] Waiting for HOME ('android.process.acore') to be launched...
[2016-01-05 00:22:18 - Emulator] emulator: UpdateCheck: current version '24.4.1', last version '24.4.1'
[2016-01-05 00:26:59 - ScanActivity] emulator-5554 disconnected! Cancelling 'com.scanlibrary.ScanActivity activity launch'!
[2016-01-05 00:27:18 - ScanActivity] ------------------------------
[2016-01-05 00:27:18 - ScanActivity] Android Launch!
[2016-01-05 00:27:18 - ScanActivity] adb is running normally.
[2016-01-05 00:27:18 - ScanActivity] Performing com.scanlibrary.ScanActivity activity launch
[2016-01-05 00:27:26 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:27:33 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:27:35 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:27:39 - ScanActivity] Success!
[2016-01-05 00:27:39 - ScanActivity] Starting activity com.scanlibrary.ScanActivity on device 7DYPCIKVEEPN5PHE
[2016-01-05 00:27:39 - ScanActivity] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.scanlibrary/.ScanActivity }
[2016-01-05 00:46:21 - OpenCV Sample - face-detection] ------------------------------
[2016-01-05 00:46:21 - OpenCV Sample - face-detection] Android Launch!
[2016-01-05 00:46:21 - OpenCV Sample - face-detection] adb is running normally.
[2016-01-05 00:46:21 - OpenCV Sample - face-detection] Performing org.opencv.samples.facedetect.FdActivity activity launch
[2016-01-05 00:46:22 - OpenCV Sample - face-detection] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:46:25 - OpenCV Sample - face-detection] Uploading OpenCV Sample - face-detection.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:46:25 - OpenCV Sample - face-detection] Installing OpenCV Sample - face-detection.apk...
[2016-01-05 00:46:27 - OpenCV Sample - face-detection] Success!
[2016-01-05 00:46:28 - OpenCV Sample - face-detection] Starting activity org.opencv.samples.facedetect.FdActivity on device 7DYPCIKVEEPN5PHE
[2016-01-05 00:46:28 - OpenCV Sample - face-detection] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.opencv.samples.facedetect/.FdActivity }
[2016-01-05 00:48:51 - ScanActivity] ------------------------------
[2016-01-05 00:48:51 - ScanActivity] Android Launch!
[2016-01-05 00:48:51 - ScanActivity] adb is running normally.
[2016-01-05 00:48:51 - ScanActivity] Performing com.scanlibrary.ScanActivity activity launch
[2016-01-05 00:48:52 - ScanActivity] Automatic Target Mode: Unable to detect device compatibility. Please select a target device.
[2016-01-05 00:48:54 - ScanActivity] WARNING: Application does not specify an API level requirement!
[2016-01-05 00:48:54 - ScanActivity] Device API version is 17 (Android 4.2.1)
[2016-01-05 00:48:54 - ScanActivity] Uploading ScanActivity.apk onto device '7DYPCIKVEEPN5PHE'
[2016-01-05 00:48:55 - ScanActivity] Installing ScanActivity.apk...
[2016-01-05 00:49:01 - ScanActivity] Success!
[2016-01-05 00:49:01 - ScanActivity] Starting activity com.scanlibrary.ScanActivity on device 7DYPCIKVEEPN5PHE
[2016-01-05 00:49:01 - ScanActivity] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.scanlibrary/.ScanActivity }

**Comment by Aliabc123** [comment]
My email id is ali87613@yahoo.com
