### ISSUE TITLE
Unable to save the capturing and crop image

### ISSUE THREAD

**Issue by amarpulli544** [jhansireddy/AndroidScannerDemo#48]
hello @nilasissen,

I am using your repository downloaded from [https://github.com/nilasissen/AndroidScannerDemo](url) .
But here when i was capture image it doesn't save and it will not process for cropping image.
I got some info through debugging see below,

```
08-20 14:35:17.604 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err: java.lang.NullPointerException: uri
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:60)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:922)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:865)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at com.scanlibrary.PickImageFragment.getBitmap(PickImageFragment.java:156)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at com.scanlibrary.PickImageFragment.onActivityResult(PickImageFragment.java:128)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:6494)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:3716)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4098)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.-wrap15(ActivityThread.java)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1360)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5443)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
08-20 14:35:17.614 3428-3428/com.fueblabs.smarthome.cheque_scandemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
How I could  resolve this issue.
System Configurations:
Android Tool : Android studio 2.3.3 
Java : Java 1.8
os : Windows 10 (64 bit).

Thanks and Regards,

Amar.

**Comment by vikasWri** [comment]
Hey, I can help you.

This is happening because of provider. can you please tell me in which device you are facing this issue and can u snippet your Manifest file here.

**Comment by jay007minz** [comment]
Hi, 
I am facing the same issue in Samsung Galaxy J2 - SM-J200G. Android version 5.1.1.

**Comment by ajay1295** [comment]
I have same problem in galaxy J7.  In emulator and other moto devices its working fine.

**Comment by nilasissen** [comment]
@amarpulli544  sorry bro it was long back I don't remember. but as far as I can remember my repo was perfectly working. maybe it's a device specific issue i have tested it mostly with moto devices.
