### ISSUE TITLE
Runtime Crash starting ScanActivity

### ISSUE THREAD

**Issue by ahusain3** [jhansireddy/AndroidScannerDemo#79]
I get the error

07-03 17:48:37.717 13467-13467/com.unikrew.photopay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.unikrew.photopay, PID: 13467
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/base.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_dependencies_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_resources_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_0_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_1_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_2_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_3_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_4_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_5_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_6_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_7_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_8_apk.apk", zip file "/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/lib/arm64, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/base.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.unikrew.photopay-Uet_gKl3G86UT8fs7KLJ6Q==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libopencv_java3.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.scanlibrary.ScanActivity.<clinit>(ScanActivity.java:125)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

I think I did something wrong while importing scanLibrary. Maybe I need to make a jar file out of the .so files in scanLibrary?

**Comment by jsonmat** [comment]
This error is exactly what I am getting. This is caused by missing .so for arm which are 64-bit. Your mobile phone has a 64-bit processor.

**Comment by scorchknight** [comment]
It should start using 32-bit libraries if no 64-bit are found right? Maybe some of the app dependancies are forcing the use of 64-bit libraries?

These are my Project dependancies

**Comment by scorchknight** [comment]
Main app dependancies

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'org.tensorflow:tensorflow-android:1.8.0'
    compile project(':scanlibrary')
}

scan Library dependancies

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
}

I imported scanLibrary as a module

**Comment by scorchknight** [comment]
Tried adding abiFilters for the ndk

android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86", "mips", "arm64"
        }
    }
}
 gave me a different error

07-04 10:34:36.992 10690-10690/com.unikrew.photopay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.unikrew.photopay, PID: 10690
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.unikrew.photopay/com.scanlibrary.ScanActivity}: java.lang.SecurityException: UID 10162 does not have permission to content://com.scanlibrary.provider/external_files/scanSample/IMG_20180704_103436.jpg [user 0]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.SecurityException: UID 10162 does not have permission to content://com.scanlibrary.provider/external_files/scanSample/IMG_20180704_103436.jpg [user 0]
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4352)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1744)
        at android.app.Activity.startActivityForResult(Activity.java:5168)
        at android.app.Activity.startActivityFromFragment(Activity.java:5144)
        at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7690)
        at android.app.Fragment.startActivityForResult(Fragment.java:1095)
        at android.app.Fragment.startActivityForResult(Fragment.java:1084)
        at com.scanlibrary.PickImageFragment.openCamera(PickImageFragment.java:129)
        at com.scanlibrary.PickImageFragment.handleIntentPreference(PickImageFragment.java:77)
        at com.scanlibrary.PickImageFragment.init(PickImageFragment.java:58)
        at com.scanlibrary.PickImageFragment.onCreateView(PickImageFragment.java:48)
        at android.app.Fragment.performCreateView(Fragment.java:2508)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1279)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3032)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2979)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:178)
        at android.app.Activity.performCreate(Activity.java:7015)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by scorchknight** [comment]
Then I changed preferences 
from 
int preference = ScanConstants.OPEN_CAMERA;

to
int preference = 0;
 The app doesn't crash it freezes for awhile then the scanActivity doesn't start

This is the red log cat

07-04 10:45:25.270 566-566/? E/mm-camera-intf: mm_channel_fsm_fn_stopped: invalid state (1) for evt (6)
07-04 10:45:25.297 560-4015/? E/msm8974_platform: ramp_speaker_gain: Could not get ctl for mixer cmd - Left Speaker Gain or Right Speaker Gain, not applying speaker gain ramp
07-04 10:45:25.297 560-4015/? D/audio_hw_primary: out_write: retry previous failed cal level set
07-04 10:45:25.297 560-4015/? W/msm8974_platform: platform_send_gain_dep_cal: Usecase list is empty
07-04 10:45:25.368 566-12041/? I/Camera3-Device: disconnect: E
07-04 10:45:25.370 566-12041/? I/QCamera3HWI: ~QCamera3HardwareInterface: stopping channel 66816
07-04 10:45:25.373 566-12041/? E/QCamera3HWI: ~QCamera3HardwareInterface: deleting channel 66816
07-04 10:45:25.376 586-12460/? E/mm-camera: mct: mct_pipeline_process_set:2304: Couldn't find stream id: 0
07-04 10:45:25.377 586-586/? E/mm-camera: port_iface_ext_unlink_func: E, identity = 0x1000f, port = 0xeef2f680, direction = 2
    port_iface_check_caps_unreserve_func:  E, identity = 0x1000f, port = 0xeef2f680, direction = 2
    iface_unreserve_sink_port: stream_id f mode 0 
    port_iface_ext_unlink_func: E, identity = 0x1000f, port = 0xeef2f980, direction = 1
    iface_ext_unlink_src_port: mct stream already removed from hw stream
    port_iface_check_caps_unreserve_func:  E, identity = 0x1000f, port = 0xeef2f980, direction = 1
    isp_port_check_caps_unreserve:844 ide 1000f port 0xeeada660
    c2d_port_check_caps_unreserve:183, identity=0x1000f
    c2d_port_check_caps_unreserve:193, identity=0x1000f, unreserved
    c2d_port_check_caps_unreserve:183, identity=0x1000f
    c2d_port_check_caps_unreserve:193, identity=0x1000f, unreserved
    cpp_port_check_caps_unreserve:164, identity=0x1000f
    cpp_port_check_caps_unreserve:174, identity=0x1000f, unreserved
    cpp_port_check_caps_unreserve:164, identity=0x1000f
    cpp_port_check_caps_unreserve:174, identity=0x1000f, unreserved
07-04 10:45:25.378 586-586/? E/mm-camera: q3a_thread_af_stop:679  q3a_thread_af_stop:679 MSG_STOP_THREAD
07-04 10:45:25.379 586-586/? D/mm-camera: stats_port_delete_reserved_stream:2426: going to NULL peer
07-04 10:45:25.382 586-12511/? E/mm-camera-isp2: isp_module_stop_session:437 session id 1
07-04 10:45:25.382 586-12513/? E/mm-camera: cpp_module_stop_session:552, info: stopping session 1 ...
07-04 10:45:25.383 586-12453/? E/mm-camera: cpp_thread_process_pipe_message:584, CPP_THREAD_MSG_ABORT: cpp_thread exiting..
07-04 10:45:25.384 586-12514/? E/mm-camera: module_faceproc_stop_session:1804] session cnt 1
07-04 10:45:25.386 586-12513/? E/mm-camera: cpp_module_stop_session:601, info: session 1 stopped.
    c2d_module_stop_session:354, info: stopping session 1 ...
07-04 10:45:25.386 586-12454/? E/mm-camera: c2d_thread_process_pipe_message:836, C2D_THREAD_MSG_ABORT: c2d_thread exiting..
07-04 10:45:25.387 586-12513/? E/mm-camera: c2d_module_stop_session:399, info: session 1 stopped.
07-04 10:45:25.388 586-12513/? E/cac2:  [cac2latency] cac2_destroy_buffers: 0 ms

**Comment by SabinaBrantner** [comment]
Do you have already solved the problem?

**Comment by SayedTalha** [comment]
any solution ?? please

**Comment by SayedTalha** [comment]
it's an issue of openCV library try to update it.

**Comment by jhansireddy** [comment]
Assuming it is with missing 64 bit architecture libraries. If so, this should be resolved since native libraries are now generated for all architectures.

**Comment by mishraaditya595** [comment]
I am getting this issue of couldn't find "libopencv_java.so". What should I do?
